DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`admin` INT(1) UNSIGNED NOT NULL DEFAULT 0,
	`salt` VARCHAR(16)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

